// Generated by gencpp from file my_cpp_service/SimpleServiceRequest.msg
// DO NOT EDIT!


#ifndef MY_CPP_SERVICE_MESSAGE_SIMPLESERVICEREQUEST_H
#define MY_CPP_SERVICE_MESSAGE_SIMPLESERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_cpp_service
{
template <class ContainerAllocator>
struct SimpleServiceRequest_
{
  typedef SimpleServiceRequest_<ContainerAllocator> Type;

  SimpleServiceRequest_()
    : message()  {
    }
  SimpleServiceRequest_(const ContainerAllocator& _alloc)
    : message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SimpleServiceRequest_

typedef ::my_cpp_service::SimpleServiceRequest_<std::allocator<void> > SimpleServiceRequest;

typedef boost::shared_ptr< ::my_cpp_service::SimpleServiceRequest > SimpleServiceRequestPtr;
typedef boost::shared_ptr< ::my_cpp_service::SimpleServiceRequest const> SimpleServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator1> & lhs, const ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator1> & lhs, const ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_cpp_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f003d6bcc824cbd51361d66d8e4f76c";
  }

  static const char* value(const ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f003d6bcc824cbdULL;
  static const uint64_t static_value2 = 0x51361d66d8e4f76cULL;
};

template<class ContainerAllocator>
struct DataType< ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_cpp_service/SimpleServiceRequest";
  }

  static const char* value(const ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n"
;
  }

  static const char* value(const ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SimpleServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_cpp_service::SimpleServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_CPP_SERVICE_MESSAGE_SIMPLESERVICEREQUEST_H
