// Generated by gencpp from file test/angle.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_ANGLE_H
#define TEST_MESSAGE_ANGLE_H

#include <ros/service_traits.h>


#include <test/angleRequest.h>
#include <test/angleResponse.h>


namespace test
{

struct angle
{

typedef angleRequest Request;
typedef angleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct angle
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::angle > {
  static const char* value()
  {
    return "fd5d4dc86797e99445f7946d14193144";
  }

  static const char* value(const ::test::angle&) { return value(); }
};

template<>
struct DataType< ::test::angle > {
  static const char* value()
  {
    return "test/angle";
  }

  static const char* value(const ::test::angle&) { return value(); }
};


// service_traits::MD5Sum< ::test::angleRequest> should match
// service_traits::MD5Sum< ::test::angle >
template<>
struct MD5Sum< ::test::angleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::angle >::value();
  }
  static const char* value(const ::test::angleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::angleRequest> should match
// service_traits::DataType< ::test::angle >
template<>
struct DataType< ::test::angleRequest>
{
  static const char* value()
  {
    return DataType< ::test::angle >::value();
  }
  static const char* value(const ::test::angleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::angleResponse> should match
// service_traits::MD5Sum< ::test::angle >
template<>
struct MD5Sum< ::test::angleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::angle >::value();
  }
  static const char* value(const ::test::angleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::angleResponse> should match
// service_traits::DataType< ::test::angle >
template<>
struct DataType< ::test::angleResponse>
{
  static const char* value()
  {
    return DataType< ::test::angle >::value();
  }
  static const char* value(const ::test::angleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_ANGLE_H
