// Generated by gencpp from file test/Person.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_PERSON_H
#define TEST_MESSAGE_PERSON_H

#include <ros/service_traits.h>


#include <test/PersonRequest.h>
#include <test/PersonResponse.h>


namespace test
{

struct Person
{

typedef PersonRequest Request;
typedef PersonResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Person
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::Person > {
  static const char* value()
  {
    return "8252a159fd1a6ef4321e6f234278121d";
  }

  static const char* value(const ::test::Person&) { return value(); }
};

template<>
struct DataType< ::test::Person > {
  static const char* value()
  {
    return "test/Person";
  }

  static const char* value(const ::test::Person&) { return value(); }
};


// service_traits::MD5Sum< ::test::PersonRequest> should match
// service_traits::MD5Sum< ::test::Person >
template<>
struct MD5Sum< ::test::PersonRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::Person >::value();
  }
  static const char* value(const ::test::PersonRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::PersonRequest> should match
// service_traits::DataType< ::test::Person >
template<>
struct DataType< ::test::PersonRequest>
{
  static const char* value()
  {
    return DataType< ::test::Person >::value();
  }
  static const char* value(const ::test::PersonRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::PersonResponse> should match
// service_traits::MD5Sum< ::test::Person >
template<>
struct MD5Sum< ::test::PersonResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::Person >::value();
  }
  static const char* value(const ::test::PersonResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::PersonResponse> should match
// service_traits::DataType< ::test::Person >
template<>
struct DataType< ::test::PersonResponse>
{
  static const char* value()
  {
    return DataType< ::test::Person >::value();
  }
  static const char* value(const ::test::PersonResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_PERSON_H
