// Generated by gencpp from file test/PersonRequest.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_PERSONREQUEST_H
#define TEST_MESSAGE_PERSONREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace test
{
template <class ContainerAllocator>
struct PersonRequest_
{
  typedef PersonRequest_<ContainerAllocator> Type;

  PersonRequest_()
    : name()
    , age(0)
    , sex(0)  {
    }
  PersonRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)
    , sex(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int8_t _age_type;
  _age_type age;

   typedef int8_t _sex_type;
  _sex_type sex;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(unknown)
  #undef unknown
#endif
#if defined(_WIN32) && defined(male)
  #undef male
#endif
#if defined(_WIN32) && defined(female)
  #undef female
#endif

  enum {
    unknown = 0,
    male = 1,
    female = 2,
  };


  typedef boost::shared_ptr< ::test::PersonRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::test::PersonRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PersonRequest_

typedef ::test::PersonRequest_<std::allocator<void> > PersonRequest;

typedef boost::shared_ptr< ::test::PersonRequest > PersonRequestPtr;
typedef boost::shared_ptr< ::test::PersonRequest const> PersonRequestConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::test::PersonRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::test::PersonRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::test::PersonRequest_<ContainerAllocator1> & lhs, const ::test::PersonRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.age == rhs.age &&
    lhs.sex == rhs.sex;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::test::PersonRequest_<ContainerAllocator1> & lhs, const ::test::PersonRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::test::PersonRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::test::PersonRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::PersonRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::test::PersonRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::PersonRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::test::PersonRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::test::PersonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d959d1ca38d5d51be053b1f8983cdb6";
  }

  static const char* value(const ::test::PersonRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d959d1ca38d5d51ULL;
  static const uint64_t static_value2 = 0xbe053b1f8983cdb6ULL;
};

template<class ContainerAllocator>
struct DataType< ::test::PersonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "test/PersonRequest";
  }

  static const char* value(const ::test::PersonRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::test::PersonRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int8 age\n"
"int8 sex\n"
"\n"
"int8 unknown = 0\n"
"int8 male = 1\n"
"int8 female = 2\n"
"\n"
;
  }

  static const char* value(const ::test::PersonRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::test::PersonRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.sex);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PersonRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::test::PersonRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::test::PersonRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<int8_t>::stream(s, indent + "  ", v.age);
    s << indent << "sex: ";
    Printer<int8_t>::stream(s, indent + "  ", v.sex);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TEST_MESSAGE_PERSONREQUEST_H
