// Generated by gencpp from file simple_cpp_service/SimpleService.msg
// DO NOT EDIT!


#ifndef SIMPLE_CPP_SERVICE_MESSAGE_SIMPLESERVICE_H
#define SIMPLE_CPP_SERVICE_MESSAGE_SIMPLESERVICE_H

#include <ros/service_traits.h>


#include <simple_cpp_service/SimpleServiceRequest.h>
#include <simple_cpp_service/SimpleServiceResponse.h>


namespace simple_cpp_service
{

struct SimpleService
{

typedef SimpleServiceRequest Request;
typedef SimpleServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SimpleService
} // namespace simple_cpp_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simple_cpp_service::SimpleService > {
  static const char* value()
  {
    return "b403fad01eab98d2beac7b71c84eadf7";
  }

  static const char* value(const ::simple_cpp_service::SimpleService&) { return value(); }
};

template<>
struct DataType< ::simple_cpp_service::SimpleService > {
  static const char* value()
  {
    return "simple_cpp_service/SimpleService";
  }

  static const char* value(const ::simple_cpp_service::SimpleService&) { return value(); }
};


// service_traits::MD5Sum< ::simple_cpp_service::SimpleServiceRequest> should match
// service_traits::MD5Sum< ::simple_cpp_service::SimpleService >
template<>
struct MD5Sum< ::simple_cpp_service::SimpleServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simple_cpp_service::SimpleService >::value();
  }
  static const char* value(const ::simple_cpp_service::SimpleServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simple_cpp_service::SimpleServiceRequest> should match
// service_traits::DataType< ::simple_cpp_service::SimpleService >
template<>
struct DataType< ::simple_cpp_service::SimpleServiceRequest>
{
  static const char* value()
  {
    return DataType< ::simple_cpp_service::SimpleService >::value();
  }
  static const char* value(const ::simple_cpp_service::SimpleServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simple_cpp_service::SimpleServiceResponse> should match
// service_traits::MD5Sum< ::simple_cpp_service::SimpleService >
template<>
struct MD5Sum< ::simple_cpp_service::SimpleServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simple_cpp_service::SimpleService >::value();
  }
  static const char* value(const ::simple_cpp_service::SimpleServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simple_cpp_service::SimpleServiceResponse> should match
// service_traits::DataType< ::simple_cpp_service::SimpleService >
template<>
struct DataType< ::simple_cpp_service::SimpleServiceResponse>
{
  static const char* value()
  {
    return DataType< ::simple_cpp_service::SimpleService >::value();
  }
  static const char* value(const ::simple_cpp_service::SimpleServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMPLE_CPP_SERVICE_MESSAGE_SIMPLESERVICE_H
