// Generated by gencpp from file simple_cpp_service/SimpleServiceResponse.msg
// DO NOT EDIT!


#ifndef SIMPLE_CPP_SERVICE_MESSAGE_SIMPLESERVICERESPONSE_H
#define SIMPLE_CPP_SERVICE_MESSAGE_SIMPLESERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simple_cpp_service
{
template <class ContainerAllocator>
struct SimpleServiceResponse_
{
  typedef SimpleServiceResponse_<ContainerAllocator> Type;

  SimpleServiceResponse_()
    : success(false)
    , message()
    , output()  {
    }
  SimpleServiceResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , output(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SimpleServiceResponse_

typedef ::simple_cpp_service::SimpleServiceResponse_<std::allocator<void> > SimpleServiceResponse;

typedef boost::shared_ptr< ::simple_cpp_service::SimpleServiceResponse > SimpleServiceResponsePtr;
typedef boost::shared_ptr< ::simple_cpp_service::SimpleServiceResponse const> SimpleServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator1> & lhs, const ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator1> & lhs, const ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace simple_cpp_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "647fe1eb929f607c9ad9e495665a07a8";
  }

  static const char* value(const ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x647fe1eb929f607cULL;
  static const uint64_t static_value2 = 0x9ad9e495665a07a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simple_cpp_service/SimpleServiceResponse";
  }

  static const char* value(const ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"float64[] output\n"
"\n"
;
  }

  static const char* value(const ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SimpleServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simple_cpp_service::SimpleServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "output[]" << std::endl;
    for (size_t i = 0; i < v.output.size(); ++i)
    {
      s << indent << "  output[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.output[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMPLE_CPP_SERVICE_MESSAGE_SIMPLESERVICERESPONSE_H
